version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - NODE_ENV=production
    volumes:
      - ./client:/app/client
    command: >
      sh -c "cd client && npm install && npm run build && cd .. && npm start"

volumes:
  mongodb_data: 